### ISSUE TITLE
`TypeSafeQueryDocumentCommand` omits ExpressionAttributeValues

### ISSUE THREAD

**Issue by volkanunsal** [sam-goodwin/typesafe-dynamodb#42]
When I use `TypeSafeQueryDocumentCommand` (`QueryCmd` in the picture), it wrongly omits `ExpressionAttributeValues` from the base type's keys. 

<img width="502" alt="Screen Shot 2022-06-25 at 12 01 19 PM" src="https://user-images.githubusercontent.com/151600/175781527-adaf2dc4-9c3e-4052-8e61-d0ef0ee7cfe9.png">

Type error:

```
Type '{ TableName: string; IndexName: string; KeyConditionExpression: string; ExpressionAttributeValues: { ':pk': string; }; }' is not assignable to type 'QueryInput<IAccount<string, string>, string | undefined, string | undefined, string | undefined, keyof IAccount<string, string> | undefined, JsonFormat.Document>'.
  Object literal may only specify known properties, and 'ExpressionAttributeValues' does not exist in type 'QueryInput<IAccount<string, string>, string | undefined, string | undefined, string | undefined, keyof IAccount<string, string> | undefined, JsonFormat.Document>'.
```

**Comment by sam-goodwin** [comment]
Interesting use-case, when I re-produce it in isolation, I don't see that error.
```ts
interface Person {
  email: string;
}

const queryperson = TypeSafeQueryDocumentCommand<Person>()

new queryperson({
  TableName: "",
  IndexName: "gsi2",
  KeyConditionExpression: `GSI2PK = :pk`,
  ExpressionAttributeValues: {
    ":pk": "email"
  }
})
```

So, I believe the root cause of this problem is `ConstructorParameters<typeof QueryCmd>[0]`.

The `QueryCommand` type determines the `ExpressionAttributeValues` based on the input data, i.e. based on the value of `KeyConditionExpression`. Since you've explicitly typed the return as `ConstructorParameters<typeof QueryCmd>[0]`, the type is not aware of `"GSI2PK = :pk"`, so it doesn't enforce the correct `ExpressionAttributeValues`.

Workaround is to use the `QueryInput` type.

```ts
interface Person {
  email: string;
}

const QueryCmd = TypeSafeQueryDocumentCommand<Person>();

function mkArgs(
  email: string
): QueryInput<
  Person,
  "GSI2PK = :pk",
  undefined,
  undefined,
  undefined,
  JsonFormat.Document
> {
  return {
    TableName: "",
    IndexName: "gsi2",
    KeyConditionExpression: `GSI2PK = :pk`,
    ExpressionAttributeValues: {
      ":pk": "email",
    },
  };
}
```
